CONFIG_NAME: 'DMM-GAN'
DATASET_NAME: 'birds'
DATA_DIR: '../data/birds'
GPU_ID: 0
WORKERS: 4
OUTPUT_PATH: '../'

TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: True
    NET_G: ''
    B_NET_D: True
    BATCH_SIZE: 8  # 22
    MAX_EPOCH: 650
    SNAPSHOT_INTERVAL: 25
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002

    NET_E: '../DAMSMencoders/text_encoder600.pth'
    SMOOTH:
        GAMMA1: 4.0  # 1,2,5 good 4 best  10&100bad
        GAMMA2: 5.0
        GAMMA3: 10.0  # 10good 1&100bad
        LAMBDA: 0.0
        LAMBDA1: 10.0 # TODO: Align hyperparameter naming and values

CAP: # TODO: All caps
    embed_size: 256
    hidden_size: 256
    num_layers: 1
    learning_rate: 0.001
    caption_cnn_path: '../STREAM/encoder-1000.ckpt'
    caption_rnn_path: '../STREAM/decoder-1000.ckpt'

GAN:
    DF_DIM: 32
    GF_DIM: 64
    Z_DIM: 100
    R_NUM: 2

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
